---
include:
  # Teclado derecho con Nice!View
  - board: eyelash_sofle_right
    shield: nice_view

  # Teclado izquierdo con Nice!View (uso normal)
  - board: eyelash_sofle_left
    shield: nice_view

  # Teclado izquierdo con ZMK Studio (desarrollo/configuración)
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left

  # Reset de configuraciones (utilidad)
  - board: nice_nano_v2
    shield: settings_reset
